version: '3.6'

services:
  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        #delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role==manager]
      labels:
      - "traefik.enable=false"
    command: ./cloud_sql_proxy -dir=/cloudsql -instances=loidoltwebhost:us-central1:swarm-sql1=tcp:0.0.0.0:3306
    volumes:
      - /mnt/loidoltdesign-swarm/cloudsql:/cloudsql
    networks:
      - database

  adminer:
    depends_on:
      - cloudsql-proxy
    image: adminer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=web"
        - "traefik.frontend.rule=Host:db.loidoltdesign.com"
    environment: 
      ADMINER_DEFAULT_SERVER: cloudsql-proxy
    networks:
      - database
      - web

networks:
  database:
    external: true
  web:
    external: true